"""Smoke tests for src/ascend/commands/roster.py (auto-generated by pact adopt)."""

import pytest

def test_import_ascend_commands_roster():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("ascend.commands.roster")
    assert mod is not None

def test_cmd_roster_list_is_callable():
    """Function cmd_roster_list exists and is callable."""
    import importlib
    mod = importlib.import_module("ascend.commands.roster")
    fn = getattr(mod, "cmd_roster_list", None)
    assert fn is not None, "'cmd_roster_list' not found in ascend.commands.roster"
    assert callable(fn)

def test_cmd_roster_add_is_callable():
    """Function cmd_roster_add exists and is callable."""
    import importlib
    mod = importlib.import_module("ascend.commands.roster")
    fn = getattr(mod, "cmd_roster_add", None)
    assert fn is not None, "'cmd_roster_add' not found in ascend.commands.roster"
    assert callable(fn)

def test_cmd_roster_edit_is_callable():
    """Function cmd_roster_edit exists and is callable."""
    import importlib
    mod = importlib.import_module("ascend.commands.roster")
    fn = getattr(mod, "cmd_roster_edit", None)
    assert fn is not None, "'cmd_roster_edit' not found in ascend.commands.roster"
    assert callable(fn)

def test_cmd_roster_show_is_callable():
    """Function cmd_roster_show exists and is callable."""
    import importlib
    mod = importlib.import_module("ascend.commands.roster")
    fn = getattr(mod, "cmd_roster_show", None)
    assert fn is not None, "'cmd_roster_show' not found in ascend.commands.roster"
    assert callable(fn)

def test_cmd_roster_flag_is_callable():
    """Function cmd_roster_flag exists and is callable."""
    import importlib
    mod = importlib.import_module("ascend.commands.roster")
    fn = getattr(mod, "cmd_roster_flag", None)
    assert fn is not None, "'cmd_roster_flag' not found in ascend.commands.roster"
    assert callable(fn)

def test_cmd_roster_unflag_is_callable():
    """Function cmd_roster_unflag exists and is callable."""
    import importlib
    mod = importlib.import_module("ascend.commands.roster")
    fn = getattr(mod, "cmd_roster_unflag", None)
    assert fn is not None, "'cmd_roster_unflag' not found in ascend.commands.roster"
    assert callable(fn)

def test_cmd_roster_search_is_callable():
    """Function cmd_roster_search exists and is callable."""
    import importlib
    mod = importlib.import_module("ascend.commands.roster")
    fn = getattr(mod, "cmd_roster_search", None)
    assert fn is not None, "'cmd_roster_search' not found in ascend.commands.roster"
    assert callable(fn)

def test_cmd_roster_import_is_callable():
    """Function cmd_roster_import exists and is callable."""
    import importlib
    mod = importlib.import_module("ascend.commands.roster")
    fn = getattr(mod, "cmd_roster_import", None)
    assert fn is not None, "'cmd_roster_import' not found in ascend.commands.roster"
    assert callable(fn)
