"""Smoke tests for src/ascend/tui/widgets/metric_bar.py (auto-generated by pact adopt)."""

import pytest

def test_import_ascend_tui_widgets_metric_bar():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("ascend.tui.widgets.metric_bar")
    assert mod is not None
