"""Smoke tests for src/ascend/commands/schedule.py (auto-generated by pact adopt)."""

import pytest

def test_import_ascend_commands_schedule():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("ascend.commands.schedule")
    assert mod is not None

def test_cmd_schedule_list_is_callable():
    """Function cmd_schedule_list exists and is callable."""
    import importlib
    mod = importlib.import_module("ascend.commands.schedule")
    fn = getattr(mod, "cmd_schedule_list", None)
    assert fn is not None, "'cmd_schedule_list' not found in ascend.commands.schedule"
    assert callable(fn)

def test_cmd_schedule_add_is_callable():
    """Function cmd_schedule_add exists and is callable."""
    import importlib
    mod = importlib.import_module("ascend.commands.schedule")
    fn = getattr(mod, "cmd_schedule_add", None)
    assert fn is not None, "'cmd_schedule_add' not found in ascend.commands.schedule"
    assert callable(fn)

def test_cmd_schedule_remove_is_callable():
    """Function cmd_schedule_remove exists and is callable."""
    import importlib
    mod = importlib.import_module("ascend.commands.schedule")
    fn = getattr(mod, "cmd_schedule_remove", None)
    assert fn is not None, "'cmd_schedule_remove' not found in ascend.commands.schedule"
    assert callable(fn)

def test_cmd_schedule_run_is_callable():
    """Function cmd_schedule_run exists and is callable."""
    import importlib
    mod = importlib.import_module("ascend.commands.schedule")
    fn = getattr(mod, "cmd_schedule_run", None)
    assert fn is not None, "'cmd_schedule_run' not found in ascend.commands.schedule"
    assert callable(fn)

def test_cmd_schedule_enable_is_callable():
    """Function cmd_schedule_enable exists and is callable."""
    import importlib
    mod = importlib.import_module("ascend.commands.schedule")
    fn = getattr(mod, "cmd_schedule_enable", None)
    assert fn is not None, "'cmd_schedule_enable' not found in ascend.commands.schedule"
    assert callable(fn)

def test_cmd_schedule_disable_is_callable():
    """Function cmd_schedule_disable exists and is callable."""
    import importlib
    mod = importlib.import_module("ascend.commands.schedule")
    fn = getattr(mod, "cmd_schedule_disable", None)
    assert fn is not None, "'cmd_schedule_disable' not found in ascend.commands.schedule"
    assert callable(fn)
