"""Smoke tests for src/ascend/tui/widgets/member_card.py (auto-generated by pact adopt)."""

import pytest

def test_import_ascend_tui_widgets_member_card():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("ascend.tui.widgets.member_card")
    assert mod is not None
