"""Smoke tests for src/ascend/tui/app.py (auto-generated by pact adopt)."""

import pytest

def test_import_ascend_tui_app():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("ascend.tui.app")
    assert mod is not None
