"""Smoke tests for src/ascend/integrations/linear.py (auto-generated by pact adopt)."""

import pytest

def test_import_ascend_integrations_linear():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("ascend.integrations.linear")
    assert mod is not None

def test_fetch_recent_issues_is_callable():
    """Function fetch_recent_issues exists and is callable."""
    import importlib
    mod = importlib.import_module("ascend.integrations.linear")
    fn = getattr(mod, "fetch_recent_issues", None)
    assert fn is not None, "'fetch_recent_issues' not found in ascend.integrations.linear"
    assert callable(fn)

def test_fetch_all_issues_is_callable():
    """Function fetch_all_issues exists and is callable."""
    import importlib
    mod = importlib.import_module("ascend.integrations.linear")
    fn = getattr(mod, "fetch_all_issues", None)
    assert fn is not None, "'fetch_all_issues' not found in ascend.integrations.linear"
    assert callable(fn)

def test_fetch_member_issues_is_callable():
    """Function fetch_member_issues exists and is callable."""
    import importlib
    mod = importlib.import_module("ascend.integrations.linear")
    fn = getattr(mod, "fetch_member_issues", None)
    assert fn is not None, "'fetch_member_issues' not found in ascend.integrations.linear"
    assert callable(fn)

def test_match_issues_is_callable():
    """Function match_issues exists and is callable."""
    import importlib
    mod = importlib.import_module("ascend.integrations.linear")
    fn = getattr(mod, "match_issues", None)
    assert fn is not None, "'match_issues' not found in ascend.integrations.linear"
    assert callable(fn)

def test_get_effective_team_ids_is_callable():
    """Function get_effective_team_ids exists and is callable."""
    import importlib
    mod = importlib.import_module("ascend.integrations.linear")
    fn = getattr(mod, "get_effective_team_ids", None)
    assert fn is not None, "'get_effective_team_ids' not found in ascend.integrations.linear"
    assert callable(fn)

def test_fetch_stale_priority_issues_is_callable():
    """Function fetch_stale_priority_issues exists and is callable."""
    import importlib
    mod = importlib.import_module("ascend.integrations.linear")
    fn = getattr(mod, "fetch_stale_priority_issues", None)
    assert fn is not None, "'fetch_stale_priority_issues' not found in ascend.integrations.linear"
    assert callable(fn)
