"""Smoke tests for src/ascend/commands/plan.py (auto-generated by pact adopt)."""

import pytest

def test_import_ascend_commands_plan():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("ascend.commands.plan")
    assert mod is not None

def test_cmd_plan_cycle_is_callable():
    """Function cmd_plan_cycle exists and is callable."""
    import importlib
    mod = importlib.import_module("ascend.commands.plan")
    fn = getattr(mod, "cmd_plan_cycle", None)
    assert fn is not None, "'cmd_plan_cycle' not found in ascend.commands.plan"
    assert callable(fn)

def test_cmd_plan_goal_create_is_callable():
    """Function cmd_plan_goal_create exists and is callable."""
    import importlib
    mod = importlib.import_module("ascend.commands.plan")
    fn = getattr(mod, "cmd_plan_goal_create", None)
    assert fn is not None, "'cmd_plan_goal_create' not found in ascend.commands.plan"
    assert callable(fn)

def test_cmd_plan_goal_list_is_callable():
    """Function cmd_plan_goal_list exists and is callable."""
    import importlib
    mod = importlib.import_module("ascend.commands.plan")
    fn = getattr(mod, "cmd_plan_goal_list", None)
    assert fn is not None, "'cmd_plan_goal_list' not found in ascend.commands.plan"
    assert callable(fn)

def test_cmd_plan_goal_update_is_callable():
    """Function cmd_plan_goal_update exists and is callable."""
    import importlib
    mod = importlib.import_module("ascend.commands.plan")
    fn = getattr(mod, "cmd_plan_goal_update", None)
    assert fn is not None, "'cmd_plan_goal_update' not found in ascend.commands.plan"
    assert callable(fn)

def test_cmd_plan_pip_create_is_callable():
    """Function cmd_plan_pip_create exists and is callable."""
    import importlib
    mod = importlib.import_module("ascend.commands.plan")
    fn = getattr(mod, "cmd_plan_pip_create", None)
    assert fn is not None, "'cmd_plan_pip_create' not found in ascend.commands.plan"
    assert callable(fn)

def test_cmd_plan_pip_show_is_callable():
    """Function cmd_plan_pip_show exists and is callable."""
    import importlib
    mod = importlib.import_module("ascend.commands.plan")
    fn = getattr(mod, "cmd_plan_pip_show", None)
    assert fn is not None, "'cmd_plan_pip_show' not found in ascend.commands.plan"
    assert callable(fn)

def test_cmd_plan_career_is_callable():
    """Function cmd_plan_career exists and is callable."""
    import importlib
    mod = importlib.import_module("ascend.commands.plan")
    fn = getattr(mod, "cmd_plan_career", None)
    assert fn is not None, "'cmd_plan_career' not found in ascend.commands.plan"
    assert callable(fn)
