"""Smoke tests for src/ascend/tui/screens/coaching.py (auto-generated by pact adopt)."""

import pytest

def test_import_ascend_tui_screens_coaching():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("ascend.tui.screens.coaching")
    assert mod is not None
