"""Smoke tests for src/ascend/cli.py (auto-generated by pact adopt)."""

import pytest

def test_import_ascend_cli():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("ascend.cli")
    assert mod is not None

def test_main_is_callable():
    """Function main exists and is callable."""
    import importlib
    mod = importlib.import_module("ascend.cli")
    fn = getattr(mod, "main", None)
    assert fn is not None, "'main' not found in ascend.cli"
    assert callable(fn)
