"""Smoke tests for contracts/src_ascend_scheduler/interface.py (auto-generated by pact adopt)."""

import pytest

def test_import_contracts_src_ascend_scheduler_interface():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("contracts.src_ascend_scheduler.interface")
    assert mod is not None

def test_schedule_to_cron_is_callable():
    """Function schedule_to_cron exists and is callable."""
    import importlib
    mod = importlib.import_module("contracts.src_ascend_scheduler.interface")
    fn = getattr(mod, "schedule_to_cron", None)
    assert fn is not None, "'schedule_to_cron' not found in contracts.src_ascend_scheduler.interface"
    assert callable(fn)

def test_parse_cron_is_callable():
    """Function parse_cron exists and is callable."""
    import importlib
    mod = importlib.import_module("contracts.src_ascend_scheduler.interface")
    fn = getattr(mod, "parse_cron", None)
    assert fn is not None, "'parse_cron' not found in contracts.src_ascend_scheduler.interface"
    assert callable(fn)

def test_compute_next_run_is_callable():
    """Function compute_next_run exists and is callable."""
    import importlib
    mod = importlib.import_module("contracts.src_ascend_scheduler.interface")
    fn = getattr(mod, "compute_next_run", None)
    assert fn is not None, "'compute_next_run' not found in contracts.src_ascend_scheduler.interface"
    assert callable(fn)

def test_describe_cron_is_callable():
    """Function describe_cron exists and is callable."""
    import importlib
    mod = importlib.import_module("contracts.src_ascend_scheduler.interface")
    fn = getattr(mod, "describe_cron", None)
    assert fn is not None, "'describe_cron' not found in contracts.src_ascend_scheduler.interface"
    assert callable(fn)

def test_generate_plist_is_callable():
    """Function generate_plist exists and is callable."""
    import importlib
    mod = importlib.import_module("contracts.src_ascend_scheduler.interface")
    fn = getattr(mod, "generate_plist", None)
    assert fn is not None, "'generate_plist' not found in contracts.src_ascend_scheduler.interface"
    assert callable(fn)

def test_write_plist_is_callable():
    """Function write_plist exists and is callable."""
    import importlib
    mod = importlib.import_module("contracts.src_ascend_scheduler.interface")
    fn = getattr(mod, "write_plist", None)
    assert fn is not None, "'write_plist' not found in contracts.src_ascend_scheduler.interface"
    assert callable(fn)

def test_load_plist_is_callable():
    """Function load_plist exists and is callable."""
    import importlib
    mod = importlib.import_module("contracts.src_ascend_scheduler.interface")
    fn = getattr(mod, "load_plist", None)
    assert fn is not None, "'load_plist' not found in contracts.src_ascend_scheduler.interface"
    assert callable(fn)

def test_unload_plist_is_callable():
    """Function unload_plist exists and is callable."""
    import importlib
    mod = importlib.import_module("contracts.src_ascend_scheduler.interface")
    fn = getattr(mod, "unload_plist", None)
    assert fn is not None, "'unload_plist' not found in contracts.src_ascend_scheduler.interface"
    assert callable(fn)

def test_remove_plist_is_callable():
    """Function remove_plist exists and is callable."""
    import importlib
    mod = importlib.import_module("contracts.src_ascend_scheduler.interface")
    fn = getattr(mod, "remove_plist", None)
    assert fn is not None, "'remove_plist' not found in contracts.src_ascend_scheduler.interface"
    assert callable(fn)
