"""Smoke tests for src/ascend/commands/sync.py (auto-generated by pact adopt)."""

import pytest

def test_import_ascend_commands_sync():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("ascend.commands.sync")
    assert mod is not None

def test_cmd_sync_is_callable():
    """Function cmd_sync exists and is callable."""
    import importlib
    mod = importlib.import_module("ascend.commands.sync")
    fn = getattr(mod, "cmd_sync", None)
    assert fn is not None, "'cmd_sync' not found in ascend.commands.sync"
    assert callable(fn)

def test_cmd_sync_github_is_callable():
    """Function cmd_sync_github exists and is callable."""
    import importlib
    mod = importlib.import_module("ascend.commands.sync")
    fn = getattr(mod, "cmd_sync_github", None)
    assert fn is not None, "'cmd_sync_github' not found in ascend.commands.sync"
    assert callable(fn)

def test_cmd_sync_linear_is_callable():
    """Function cmd_sync_linear exists and is callable."""
    import importlib
    mod = importlib.import_module("ascend.commands.sync")
    fn = getattr(mod, "cmd_sync_linear", None)
    assert fn is not None, "'cmd_sync_linear' not found in ascend.commands.sync"
    assert callable(fn)

def test_cmd_sync_slack_is_callable():
    """Function cmd_sync_slack exists and is callable."""
    import importlib
    mod = importlib.import_module("ascend.commands.sync")
    fn = getattr(mod, "cmd_sync_slack", None)
    assert fn is not None, "'cmd_sync_slack' not found in ascend.commands.sync"
    assert callable(fn)

def test_cmd_sync_snapshot_is_callable():
    """Function cmd_sync_snapshot exists and is callable."""
    import importlib
    mod = importlib.import_module("ascend.commands.sync")
    fn = getattr(mod, "cmd_sync_snapshot", None)
    assert fn is not None, "'cmd_sync_snapshot' not found in ascend.commands.sync"
    assert callable(fn)

def test_cmd_sync_backfill_is_callable():
    """Function cmd_sync_backfill exists and is callable."""
    import importlib
    mod = importlib.import_module("ascend.commands.sync")
    fn = getattr(mod, "cmd_sync_backfill", None)
    assert fn is not None, "'cmd_sync_backfill' not found in ascend.commands.sync"
    assert callable(fn)
