"""Smoke tests for src/ascend/commands/init.py (auto-generated by pact adopt)."""

import pytest

def test_import_ascend_commands_init():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("ascend.commands.init")
    assert mod is not None

def test_cmd_init_is_callable():
    """Function cmd_init exists and is callable."""
    import importlib
    mod = importlib.import_module("ascend.commands.init")
    fn = getattr(mod, "cmd_init", None)
    assert fn is not None, "'cmd_init' not found in ascend.commands.init"
    assert callable(fn)

def test_cmd_doctor_is_callable():
    """Function cmd_doctor exists and is callable."""
    import importlib
    mod = importlib.import_module("ascend.commands.init")
    fn = getattr(mod, "cmd_doctor", None)
    assert fn is not None, "'cmd_doctor' not found in ascend.commands.init"
    assert callable(fn)

def test_cmd_config_show_is_callable():
    """Function cmd_config_show exists and is callable."""
    import importlib
    mod = importlib.import_module("ascend.commands.init")
    fn = getattr(mod, "cmd_config_show", None)
    assert fn is not None, "'cmd_config_show' not found in ascend.commands.init"
    assert callable(fn)

def test_cmd_config_set_is_callable():
    """Function cmd_config_set exists and is callable."""
    import importlib
    mod = importlib.import_module("ascend.commands.init")
    fn = getattr(mod, "cmd_config_set", None)
    assert fn is not None, "'cmd_config_set' not found in ascend.commands.init"
    assert callable(fn)
