"""Smoke tests for contracts/contracts_src_ascend_output_interface/interface.py (auto-generated by pact adopt)."""

import pytest

def test_import_contracts_contracts_src_ascend_output_interface_interface():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("contracts.contracts_src_ascend_output_interface.interface")
    assert mod is not None

def test_print_report_is_callable():
    """Function print_report exists and is callable."""
    import importlib
    mod = importlib.import_module("contracts.contracts_src_ascend_output_interface.interface")
    fn = getattr(mod, "print_report", None)
    assert fn is not None, "'print_report' not found in contracts.contracts_src_ascend_output_interface.interface"
    assert callable(fn)

def test_print_json_is_callable():
    """Function print_json exists and is callable."""
    import importlib
    mod = importlib.import_module("contracts.contracts_src_ascend_output_interface.interface")
    fn = getattr(mod, "print_json", None)
    assert fn is not None, "'print_json' not found in contracts.contracts_src_ascend_output_interface.interface"
    assert callable(fn)

def test_print_status_is_callable():
    """Function print_status exists and is callable."""
    import importlib
    mod = importlib.import_module("contracts.contracts_src_ascend_output_interface.interface")
    fn = getattr(mod, "print_status", None)
    assert fn is not None, "'print_status' not found in contracts.contracts_src_ascend_output_interface.interface"
    assert callable(fn)

def test_copy_to_clipboard_is_callable():
    """Function copy_to_clipboard exists and is callable."""
    import importlib
    mod = importlib.import_module("contracts.contracts_src_ascend_output_interface.interface")
    fn = getattr(mod, "copy_to_clipboard", None)
    assert fn is not None, "'copy_to_clipboard' not found in contracts.contracts_src_ascend_output_interface.interface"
    assert callable(fn)

def test_format_table_is_callable():
    """Function format_table exists and is callable."""
    import importlib
    mod = importlib.import_module("contracts.contracts_src_ascend_output_interface.interface")
    fn = getattr(mod, "format_table", None)
    assert fn is not None, "'format_table' not found in contracts.contracts_src_ascend_output_interface.interface"
    assert callable(fn)

def test_render_output_is_callable():
    """Function render_output exists and is callable."""
    import importlib
    mod = importlib.import_module("contracts.contracts_src_ascend_output_interface.interface")
    fn = getattr(mod, "render_output", None)
    assert fn is not None, "'render_output' not found in contracts.contracts_src_ascend_output_interface.interface"
    assert callable(fn)
