"""Smoke tests for src/ascend/commands/team.py (auto-generated by pact adopt)."""

import pytest

def test_import_ascend_commands_team():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("ascend.commands.team")
    assert mod is not None

def test_cmd_team_list_is_callable():
    """Function cmd_team_list exists and is callable."""
    import importlib
    mod = importlib.import_module("ascend.commands.team")
    fn = getattr(mod, "cmd_team_list", None)
    assert fn is not None, "'cmd_team_list' not found in ascend.commands.team"
    assert callable(fn)

def test_cmd_team_create_is_callable():
    """Function cmd_team_create exists and is callable."""
    import importlib
    mod = importlib.import_module("ascend.commands.team")
    fn = getattr(mod, "cmd_team_create", None)
    assert fn is not None, "'cmd_team_create' not found in ascend.commands.team"
    assert callable(fn)

def test_cmd_team_add_is_callable():
    """Function cmd_team_add exists and is callable."""
    import importlib
    mod = importlib.import_module("ascend.commands.team")
    fn = getattr(mod, "cmd_team_add", None)
    assert fn is not None, "'cmd_team_add' not found in ascend.commands.team"
    assert callable(fn)

def test_cmd_team_show_is_callable():
    """Function cmd_team_show exists and is callable."""
    import importlib
    mod = importlib.import_module("ascend.commands.team")
    fn = getattr(mod, "cmd_team_show", None)
    assert fn is not None, "'cmd_team_show' not found in ascend.commands.team"
    assert callable(fn)
