"""Meeting Summarizer — uses Claude API to process meeting transcripts.

Generated by Pact contract-first pipeline, adapted for Ascend integration.
"""

from __future__ import annotations

import json
import logging
import os
import re
from enum import Enum
from typing import Any, Optional

import anthropic
from pydantic import BaseModel, field_validator

from ascend.audit import log_operation
from ascend.config import AscendConfig

logger = logging.getLogger(__name__)

_MAX_INPUT_CHARS = 100_000

_SUMMARY_SYSTEM_PROMPT = (
    "You are a meeting summarizer. Given a meeting transcript, produce a concise "
    "2-4 sentence summary capturing the key points, decisions, and action items."
)

_EXTRACT_SYSTEM_PROMPT = (
    "You are a meeting analyst. Given a meeting transcript, extract structured items "
    "as a JSON array. Each item must have: 'kind' (one of: action_item, decision, "
    "topic, concern, win), 'content' (non-empty string), and 'owner' (string or null). "
    "Return ONLY a valid JSON array, no other text."
)

_SENTIMENT_SYSTEM_PROMPT = (
    "You are a sentiment analyzer. Given a meeting transcript, analyze the overall "
    "sentiment and return ONLY a JSON object with a single key 'score' whose value "
    'is a float between 0.0 (very negative) and 1.0 (very positive). Example: {"score": 0.75}'
)

_PREP_SYSTEM_PROMPT = (
    "You are a 1:1 meeting preparation assistant. Given context about a team member "
    "including recent meetings, open action items, and optional performance data, "
    "generate a structured conversation preparation plan for an upcoming 1:1 meeting."
)


class MeetingItemKind(str, Enum):
    action_item = "action_item"
    decision = "decision"
    topic = "topic"
    concern = "concern"
    win = "win"


class MeetingItemExtract(BaseModel):
    kind: MeetingItemKind
    content: str
    owner: Optional[str] = None

    @field_validator("content")
    @classmethod
    def content_must_be_nonempty(cls, v: str) -> str:
        if not v:
            raise ValueError("content must be non-empty")
        return v


def _truncate(text: str) -> str:
    if len(text) <= _MAX_INPUT_CHARS:
        return text
    truncated = text[:_MAX_INPUT_CHARS]
    last_period = truncated.rfind(". ")
    if last_period > _MAX_INPUT_CHARS // 2:
        truncated = truncated[:last_period + 1]
    return truncated + " [TRUNCATED]"


def _parse_json(text: str) -> Any:
    stripped = text.strip()
    fence_pattern = re.compile(r"^```(?:json)?\s*\n?(.*?)\n?\s*```$", re.DOTALL)
    m = fence_pattern.match(stripped)
    if m:
        stripped = m.group(1).strip()
    return json.loads(stripped)


def get_client(config: AscendConfig) -> Optional[anthropic.Anthropic]:
    """Create an anthropic client from env var. Returns None if unavailable."""
    try:
        api_key = os.environ.get(config.anthropic_api_key_env, "")
        if not api_key:
            logger.warning("API key env var '%s' is not set or empty", config.anthropic_api_key_env)
            return None
        return anthropic.Anthropic(api_key=api_key)
    except Exception:
        logger.error("Unexpected error creating Anthropic client", exc_info=True)
        return None


def summarize_transcript(
    raw_text: str,
    config: AscendConfig,
    client: Optional[anthropic.Anthropic] = None,
) -> Optional[str]:
    """Summarize a meeting transcript. Returns None on any failure."""
    try:
        if not raw_text or not raw_text.strip():
            return None
        if client is None:
            client = get_client(config)
        if client is None:
            return None

        response = client.messages.create(
            model=config.model, max_tokens=4096,
            system=_SUMMARY_SYSTEM_PROMPT,
            messages=[{"role": "user", "content": _truncate(raw_text)}],
        )
        result = response.content[0].text
        log_operation("summarize_transcript", result="success")
        return result if result else None
    except Exception:
        logger.error("Error in summarize_transcript", exc_info=True)
        log_operation("summarize_transcript", error="failed")
        return None


def extract_items(
    raw_text: str,
    config: AscendConfig,
    client: Optional[anthropic.Anthropic] = None,
) -> list[dict[str, Any]]:
    """Extract structured meeting items. Returns [] on any failure."""
    try:
        if not raw_text or not raw_text.strip():
            return []
        if client is None:
            client = get_client(config)
        if client is None:
            return []

        response = client.messages.create(
            model=config.model, max_tokens=4096,
            system=_EXTRACT_SYSTEM_PROMPT,
            messages=[{"role": "user", "content": _truncate(raw_text)}],
        )
        try:
            parsed = _parse_json(response.content[0].text)
        except (json.JSONDecodeError, ValueError):
            logger.warning("Malformed JSON response from Claude in extract_items")
            return []

        if not isinstance(parsed, list):
            return []

        items: list[dict[str, Any]] = []
        for raw_item in parsed:
            if not isinstance(raw_item, dict):
                continue
            try:
                validated = MeetingItemExtract(**raw_item)
                items.append(validated.model_dump())
            except Exception:
                logger.warning("Dropping invalid item: %s", raw_item)
        log_operation("extract_items", result=f"extracted {len(items)} items")
        return items
    except Exception:
        logger.error("Error in extract_items", exc_info=True)
        return []


def analyze_sentiment(
    raw_text: str,
    config: AscendConfig,
    client: Optional[anthropic.Anthropic] = None,
) -> Optional[float]:
    """Analyze sentiment. Returns float in [0.0, 1.0] or None."""
    try:
        if not raw_text or not raw_text.strip():
            return None
        if client is None:
            client = get_client(config)
        if client is None:
            return None

        response = client.messages.create(
            model=config.model, max_tokens=256,
            system=_SENTIMENT_SYSTEM_PROMPT,
            messages=[{"role": "user", "content": _truncate(raw_text)}],
        )
        raw_response = response.content[0].text
        score = None
        try:
            parsed = _parse_json(raw_response)
            if isinstance(parsed, dict) and "score" in parsed:
                score = float(parsed["score"])
            elif isinstance(parsed, (int, float)):
                score = float(parsed)
        except (json.JSONDecodeError, ValueError, TypeError):
            try:
                score = float(raw_response.strip())
            except (ValueError, TypeError):
                return None

        if score is None:
            return None
        if score < 0.0 or score > 1.0:
            logger.warning("Sentiment score %.4f out of range, clamping", score)
            score = max(0.0, min(1.0, score))

        log_operation("analyze_sentiment", result="success")
        return score
    except Exception:
        logger.error("Error in analyze_sentiment", exc_info=True)
        return None


def generate_prep(
    member_name: str,
    recent_meetings: list[dict],
    open_items: list[dict],
    performance_data: Optional[dict] = None,
    config: Optional[AscendConfig] = None,
    client: Optional[anthropic.Anthropic] = None,
) -> Optional[str]:
    """Generate a 1:1 prep plan. Returns None on any failure."""
    try:
        if not member_name or not member_name.strip():
            return None
        if config is None:
            from ascend.config import load_config
            config = load_config()
        if client is None:
            client = get_client(config)
        if client is None:
            return None

        parts = [f"Prepare for an upcoming 1:1 meeting with {member_name.strip()}."]

        if recent_meetings:
            parts.append("\n## Recent Meetings")
            for mtg in recent_meetings:
                parts.append(f"\n### {mtg.get('date', 'Unknown date')}")
                if mtg.get("summary"):
                    parts.append(f"Summary: {mtg['summary']}")
                for item in mtg.get("items", []):
                    parts.append(f"- [{item.get('kind', '?')}] {item.get('content', '')}")

        if open_items:
            parts.append("\n## Open Action Items")
            for item in open_items:
                parts.append(f"- {item.get('content', '')} (from {item.get('date', '?')})")

        if performance_data:
            parts.append("\n## Performance Data")
            if performance_data.get("goals"):
                parts.append("Goals: " + "; ".join(performance_data["goals"]))
            if performance_data.get("flags"):
                parts.append("Flags: " + "; ".join(performance_data["flags"]))
            if performance_data.get("notes"):
                parts.append(f"Notes: {performance_data['notes']}")

        response = client.messages.create(
            model=config.model, max_tokens=4096,
            system=_PREP_SYSTEM_PROMPT,
            messages=[{"role": "user", "content": _truncate("\n".join(parts))}],
        )
        result = response.content[0].text
        log_operation("generate_prep", result="success")
        return result if result else None
    except Exception:
        logger.error("Error in generate_prep", exc_info=True)
        return None
