"""Transcript parser for Ascend meeting transcripts.

Parses meeting transcript files (.txt, .md) into structured data.
Pure parsing functions + DB-aware helpers for member resolution.
Generated by Pact contract-first pipeline, adapted for Ascend integration.
"""

import datetime
import logging
import re
import sqlite3
from difflib import SequenceMatcher
from pathlib import Path
from typing import Optional

from pydantic import BaseModel, ConfigDict, Field

logger = logging.getLogger(__name__)

# Module-level compiled regex for speaker turn detection
SPEAKER_PATTERN = re.compile(r'^(?:\*\*)?([A-Za-z][A-Za-z .\'\-]{1,59})(?:\*\*)?\s*:\s*(.+)')

# Filename pattern: YYYY-MM-DD_First_Last.ext
FILENAME_DATE_PATTERN = re.compile(r'^(\d{4}-\d{2}-\d{2})(?:_(.+?))?\.(?:txt|md)$', re.IGNORECASE)

# Content date pattern
CONTENT_DATE_PATTERN = re.compile(r'(\d{4}-\d{2}-\d{2})')

MAX_RAW_TEXT = 100_000
FUZZY_THRESHOLD = 0.6


class TranscriptError(ValueError):
    """Custom exception for transcript parsing failures."""
    FILE_NOT_FOUND = "FILE_NOT_FOUND"
    FILE_UNREADABLE = "FILE_UNREADABLE"
    EMPTY_TRANSCRIPT = "EMPTY_TRANSCRIPT"
    INVALID_FORMAT = "INVALID_FORMAT"
    DIRECTORY_NOT_FOUND = "DIRECTORY_NOT_FOUND"

    def __init__(self, message: str, variant: str) -> None:
        super().__init__(message)
        self.variant = variant


class TranscriptTurn(BaseModel):
    """A single speaker turn in a transcript. Frozen (immutable)."""
    model_config = ConfigDict(frozen=True)
    speaker: str
    text: str


class ParsedTranscript(BaseModel):
    """Structured representation of a parsed meeting transcript."""
    source_file: str
    raw_text: str = Field(exclude=True)
    turns: list[TranscriptTurn]
    date: Optional[str] = None
    member_name: Optional[str] = None
    member_id: Optional[int] = None


def parse_transcript(file_path: Path) -> ParsedTranscript:
    """Read a transcript file and parse it into a ParsedTranscript."""
    if not file_path.exists():
        raise TranscriptError(f"File not found: {file_path}", TranscriptError.FILE_NOT_FOUND)

    if not file_path.is_file():
        raise TranscriptError(f"Not a file: {file_path}", TranscriptError.INVALID_FORMAT)

    try:
        raw_text = file_path.read_text(encoding="utf-8", errors="replace")
    except (PermissionError, OSError) as exc:
        raise TranscriptError(f"Cannot read file: {file_path}: {exc}", TranscriptError.FILE_UNREADABLE) from exc

    if not raw_text.strip():
        raise TranscriptError(f"Empty transcript: {file_path}", TranscriptError.EMPTY_TRANSCRIPT)

    if len(raw_text) > MAX_RAW_TEXT:
        logger.warning("Transcript %s exceeds %d chars, truncating", file_path.name, MAX_RAW_TEXT)
        raw_text = raw_text[:MAX_RAW_TEXT]

    turns: list[TranscriptTurn] = []
    for line in raw_text.splitlines():
        match = SPEAKER_PATTERN.match(line)
        if match:
            speaker = match.group(1).strip()
            text = match.group(2).strip()
            turns.append(TranscriptTurn(speaker=speaker, text=text))
        else:
            stripped = line.strip()
            if stripped and turns:
                prev = turns[-1]
                turns[-1] = TranscriptTurn(speaker=prev.speaker, text=prev.text + "\n" + stripped)

    filename = file_path.name
    date = detect_date(filename, raw_text)

    member_name: Optional[str] = None
    fn_match = FILENAME_DATE_PATTERN.match(filename)
    if fn_match and fn_match.group(2):
        member_name = fn_match.group(2).replace("_", " ")

    return ParsedTranscript(
        source_file=filename, raw_text=raw_text, turns=turns,
        date=date, member_name=member_name, member_id=None,
    )


def detect_date(filename: str, content: str) -> Optional[str]:
    """Extract a meeting date from filename or content."""
    fn_match = re.match(r'^(\d{4}-\d{2}-\d{2})', filename)
    if fn_match:
        candidate = fn_match.group(1)
        if _validate_date(candidate):
            return candidate

    lines = content.splitlines()[:20]
    for line in lines:
        match = CONTENT_DATE_PATTERN.search(line)
        if match:
            candidate = match.group(1)
            if _validate_date(candidate):
                return candidate
    return None


def resolve_member(
    speaker_names: list[str],
    manager_name: Optional[str],
    db_conn: sqlite3.Connection,
) -> Optional[int]:
    """Match speaker names against members DB to find the meeting subject."""
    try:
        rows = db_conn.execute("SELECT id, name, email, slack FROM members").fetchall()
    except sqlite3.Error as exc:
        raise TranscriptError(f"Database error: {exc}", TranscriptError.INVALID_FORMAT) from exc

    members = []
    for row in rows:
        mid = row[0] if isinstance(row, tuple) else row["id"]
        name = row[1] if isinstance(row, tuple) else row["name"]
        email = row[2] if isinstance(row, tuple) else row["email"]
        slack = row[3] if isinstance(row, tuple) else row["slack"]
        email_prefix = email.split("@")[0] if email else None
        members.append({
            "id": mid, "name": name,
            "name_lower": name.lower(),
            "email_prefix": email_prefix.lower() if email_prefix else None,
            "slack": slack.lower() if slack else None,
        })

    manager_lower = manager_name.lower() if manager_name else None

    for speaker in speaker_names:
        speaker_lower = speaker.lower()
        for m in members:
            if manager_lower and m["name_lower"] == manager_lower:
                continue
            if (speaker_lower == m["name_lower"]
                    or speaker_lower == m["email_prefix"]
                    or speaker_lower == m["slack"]):
                return m["id"]

    for speaker in speaker_names:
        speaker_lower = speaker.lower()
        for m in members:
            if manager_lower and m["name_lower"] == manager_lower:
                continue
            ratio = SequenceMatcher(None, speaker_lower, m["name_lower"]).ratio()
            if ratio >= FUZZY_THRESHOLD:
                return m["id"]

    return None


def scan_directory(dir_path: Path) -> list[Path]:
    """Find all transcript files (.txt, .md) in a directory (non-recursive)."""
    if not dir_path.exists():
        raise TranscriptError(f"Directory not found: {dir_path}", TranscriptError.DIRECTORY_NOT_FOUND)
    if not dir_path.is_dir():
        raise TranscriptError(f"Not a directory: {dir_path}", TranscriptError.DIRECTORY_NOT_FOUND)

    result: list[Path] = []
    for entry in dir_path.iterdir():
        if not entry.is_file():
            continue
        if entry.name.startswith("."):
            continue
        if entry.suffix.lower() not in (".txt", ".md"):
            continue
        if entry.stat().st_size == 0:
            continue
        result.append(entry)

    result.sort(key=lambda p: p.name)
    return result


def check_duplicate(
    source_file: str,
    member_id: Optional[int],
    date: Optional[str],
    db_conn: sqlite3.Connection,
) -> bool:
    """Check if a transcript has already been ingested."""
    try:
        row = db_conn.execute(
            "SELECT COUNT(*) FROM meetings WHERE source_file = ? AND member_id IS ? AND date IS ?",
            (source_file, member_id, date),
        ).fetchone()
    except sqlite3.Error as exc:
        raise TranscriptError(f"Database error: {exc}", TranscriptError.INVALID_FORMAT) from exc
    return row[0] > 0


def _validate_date(candidate: str) -> bool:
    try:
        datetime.date.fromisoformat(candidate)
        return True
    except ValueError:
        return False
